// src/app/board/uiText.ts
//
// /board の UI 文言辞書（page.tsx から抽出、2026-07-23 コンテキスト効率化）。
// キーは en を正とし、UiKey は en のキー集合から導出する。

export type Lang = "ja" | "en";

export const UI_TEXT = {
  en: {
    title: "Board Export",
    language: "Language",
    ja: "日本語",
    en: "EN",

    template: "Template",
    players: "Players",
    expansionBase: "Base game",
    expansionLF: "Lost Fleet",
    placementMethod: "Placement",
    method1: "Method 1 (swap outer 05-10 only)",
    method2: "Method 2 (also swap inner 01-04)",
    method3: "Method 3 (swap all 10 tiles)",
    placementMethodTip:
      "Rulebook p.19: Method 1 keeps sectors 01-04 in their first-game positions and shuffles 05-10; Method 2 also shuffles 01-04 within the inner slots; Method 3 shuffles all 10 tiles. All tiles rotate freely in every method.",
    wGaiaD1: "Gaia dist 1",
    wGaiaD2: "Gaia dist 2",
    wGaiaD3: "Gaia dist 3",
    wGaiaTip:
      "For each coloured planet, every gaia planet at distance 1/2/3 adds this weight to that colour (all gaia summed).",
    wClusterSize: "Cluster weight",
    wClusterTip:
      "For each connected planet cluster of size n>=2 (gaia/transdim join clusters), every colour in it gains +n x this weight (once per colour).",
    seed: "Seed",
    randomSeed: "Random Seed",
    seedMode: "Seed mode",
    seedModeRandom: "Random",
    seedModeFixed: "Fixed (use Seed)",

    runSearch: "Run Search (LogicalMap)",
    searching: "Searching...",

    continuous: "Continuous",
    stopSearch: "Stop",
    hash: "Hash",
    apply: "Apply",
    copy: "Copy",
    copyUrl: "Copy URL",
    shareUrl: "Share URL",
    shareUrlCopied: "Copied to clipboard",
    hashNotFound: "Hash not found in current results.",

    progress: "progress",
    best: "best",
    selectedSeed: "selected seed",

    searchSsot: "Search SSOT",
    noSearchConfig: `No search config for templateId. Add it in src/gaia/ssot/searchPlacementConfig.ts`,
    templateMismatch:
      "The board does not belong to the selected template, so markers fall back to tile level. Match the players/expansion radios to the board.",

    currentPlacementHash: "current placementHash",
    fixedLarge: "fixedLarge",
    littlePool: "littlePool",
    scoutCount: "scoutCount",

    logicalResults: "LogicalMap Results (SSOT)",
    currentLogicalSummary: "Current Logical Summary",
    noCurrentResult: "No current result (run search or select a Top-K item).",

    placementHashResult: "placementHash(result)",
    placementHashView: "placementHash(view)",
    score: "score",
    rawScore: "rawScore",
    rankScore: "Score",
    imbalance: "imbalance",
    outerCnt: "outerCnt",
    touchCnt: "touchCnt",

    trials: "Trials",
    topK: "Top-K",
    totalSearched: "totalSearched",
    speed: "speed",
    eta: "eta",

    resultsMode: "Results",
    resultsModeActive: "Top-K (Active)",
    resultsModeUsed: "Used",
    markUsed: "Mark used",
    showing: "Showing",
    pin: "Pin",
    unpin: "Unpin",
    restore: "Restore",
    delete: "Delete",
    saved: "saved",
    savedConditions: "Saved conditions",
    tileModeLabel: "Board view",
    tileImage: "Images",
    tileSchematic: "Number + rotation",
    resetConditions: "Start fresh (defaults)",
    resetConditionsTip:
      "Reset every search condition to its default. Saved conditions are auto-applied on launch, so use this to pick up new defaults. Saved maps and conditions are NOT deleted; players/expansion are left alone.",
    confirmResetConditions: "Reset all search conditions to their defaults?",
    savedConditionsShow: "Show",
    savedConditionsHide: "Hide",
    applyCondition: "Apply",
    deleteMeta: "Delete condition only",    deleteAll: "Delete condition + maps",

    mapTools: "Map tools",
    displaySettings: "Display settings",

    exportImportTitle: "Export / Import",
    exportAll: "Export all",
    exportCurrent: "Export current condition",
    importMode: "Import mode",
    importMerge: "Merge",
    importReplace: "Replace (danger)",
    importReplaceWarn: "This will delete all saved data and then import.",
    importChooseFile: "Choose JSON file",
    importRun: "Import",
    importPreviewTitle: "Import preview",
    importPreviewValid: "Valid",
    importPreviewInvalid: "Invalid",
    importPreviewExportedAt: "Exported at",
    importPreviewProfiles: "Profiles",
    importPreviewCandidates: "Candidates",
    importPreviewSearchKeys: "Search keys",
    importPreviewProfileConflicts: "Profiles already exist",
    importPreviewCandidateConflicts: "Candidates already exist",
    importPreviewFixups: "Auto-fixes",
    importPreviewFixupsRank: "rankValue filled",
    importPreviewFixupsUsedKey: "usedKey filled",
    importPreviewFixupsId: "id filled",
    importReplaceConfirmLabel: "Type DELETE to enable Replace",
    importTooLargeNote: "Note: conflict scan is capped for very large files.",

    exportDone: "Exported",
    importDone: "Imported",
    importError: "Import error",
    confirmDeleteMeta: "Delete this saved condition metadata? (Maps will be kept.)",
    confirmDeleteAll: "Delete this saved condition and ALL saved maps for it? This cannot be undone.",
    legacyUnknown: "Legacy (params unavailable)",
    conditionName: "Name",
    unnamed: "(unnamed)",
    editName: "Edit",
    saveName: "Save",
    cancelName: "Cancel",
    namePlaceholder: "e.g. tournament / wScout high",
    filter: "Filter",
    filterPlaceholder: "Search name / params (e.g. wScout=6, std)",
    templateAll: "All",
    clear: "Clear",


    hard: "Hard",
    outerSameColorMax: "Outer same-color max",
    centerMode: "Center mode",
    maxConnectedPlanets: "Max planet cluster",
    h5IncludeScouts: "Include scouts",

    soft: "Soft",
    metric: "Metric",
    radius: "Radius",
    scoutRadiusLabel: "Scout radius",
    wOuter: "wOuter",
    wTouch: "wTouch",
    wScout: "wScout",
    wScoutCore: "wScoutCore",
wScoutS1: "wScout (twilight)",
wScoutS2: "wScout (eclipse)",
wScoutS3: "wScout (rebellion)",
wScoutS4: "wScout (tfmars)",
wScoutCoreS1: "wScoutCore (twilight)",
wScoutCoreS2: "wScoutCore (eclipse)",
wScoutCoreS3: "wScoutCore (rebellion)",
wScoutCoreS4: "wScoutCore (tfmars)",
scoutCoreAttribBest: "ScoutCore attribution: best",

    colorPreference: "Color preference",
    wColorPref: "ColorPref weight",

    scoutCoreRadius: "scoutCore radius",
    scoutCoreTotal: "scoutCore total",
    scoutRadius: "scout radius",
    scoutTotal: "scout total",

    breakdown: "breakdown (Logical)",

    topKLogical: "Top-K (Logical)",

    hardFailCounts: "Hard fail counts",

    glossary: "Glossary",
    show: "show",
    hide: "hide",
    algoVersion: "Algo version",
    evalVersion: "Eval version",
    oldDataAvailable: "Old saved data found for this condition (different version)",
    copyFrom: "Copy from",
    confirmCopy: "Copy candidates from an older version into the current version? (Scores are not re-evaluated)",
    extra: "extra",

    // --- hover hints (⑤ UI wording, 2026-07-24). Shown via title=. ---
    tipTrials: "Boards generated and evaluated per search run",
    tipTopK: "How many top results are kept and shown",
    tipContinuous: "Repeats searches until stopped, accumulating top results",
    tipHard: "Constraints that immediately reject a board",
    tipSoft: "Weights that rank the surviving boards",
    tipOuterSameColorMax: "Max planets of the same color allowed on the outermost ring",
    tipMaxConnectedPlanets:
      "0 = no limit. With N, boards containing a connected planet cluster larger than N are rejected (gaia/transdim count as connected)",
    tipH5IncludeScouts: "Scout cells also join clusters for the check above",
    tipCenterMode: "Restricts which tile may occupy the center slot",
    tipWOuter: "Weight per planet on the outermost ring (added to that color's total)",
    tipWTouch: "Weight per planet one ring inside the outermost",
    tipWScoutShip: "Weight per planet within the scout radius of this ship",
    tipWScoutCoreShip:
      "Weight for planets within distance 1-2 of this ship's touched planets. Only planets that have TWO OR MORE touched planets within that range qualify (d=1: weight, d=2: weight-1; contributions are summed). Gaia and transdimensional planets never count as touched planets.",
    tipScoutRadius: "Distance within which a planet counts as touching a scout",
    tipScoutCoreAttrib: "A planet in several ships' range is credited only to the highest-contribution ship",
    tipColorPref: "+ favors boards where that color is strong, - penalizes it (weight x color total added to the score)",
    tipScore: "Higher when the seven colors are close in strength (small imbalance)",
    tipHashPair:
      "HASH(eval) = board of the selected search result / HASH(view) = board currently displayed. They differ only after manual seed edits or shared links",
    tipOuterCnt: "Planets on the outermost ring",
    tipTouchCnt: "Planets one ring inside the outermost",
    tipResultsActive: "Top saved maps for the current condition",
    tipResultsUsed: "Maps you marked as used (kept out of the top list)",
    tipPin: "Pinned maps appear in the List tab and are protected from capacity trimming",
    tipMarkUsed: "Move to the Used list (e.g. already played)",
    tipTotalCol: "Sum of all evaluation axes for that color",
    extraAxesLF: "Gaia proximity / cluster axes",
    tipExtraAxesLF:
      "Use the base-game gaia-proximity and star-cluster axes for Lost Fleet too. On by default. Turning it off drops both axes from the key and returns to the older Lost Fleet result bucket (old maps stay available to copy).",
  },
  ja: {
    title: "ボード表示（確認用）",
    language: "言語",
    ja: "日本語",
    en: "EN",

    template: "テンプレート",
    players: "人数",
    expansionBase: "基本版",
    expansionLF: "Lost Fleet",
    placementMethod: "配置方法",
    method1: "方法1（外側05-10のみ入替）",
    method2: "方法2（内側01-04も入替）",
    method3: "方法3（全10タイル入替）",
    placementMethodTip:
      "ルールブックp19: 方法1は01-04を最初のゲームの位置に固定し05-10を入替。方法2は01-04も内側4スロット内で入替。方法3は全10タイルを入替。回転はどの方法でも全タイル自由。",
    wGaiaD1: "ガイア距離1",
    wGaiaD2: "ガイア距離2",
    wGaiaD3: "ガイア距離3",
    wGaiaTip:
      "各色惑星から距離1/2/3にあるガイア惑星1個ごとに、この重みをその色に加点（全ガイア合算）。",
    wClusterSize: "星系評価",
    wClusterTip:
      "サイズn≧2の連結惑星クラスタ（ガイア/次元横断も連結に含む）に含まれる各色に +n×この重み を加点（色ごとに1回）。",
    seed: "シード",
    randomSeed: "ランダムシード",
    seedMode: "シード指定",
    seedModeRandom: "ランダム",
    seedModeFixed: "固定（入力seed）",

    runSearch: "検索実行",
    searching: "検索中...",

    continuous: "連続検索",
    stopSearch: "停止",
    hash: "Hash",
    apply: "適用",
    copy: "コピー",
    copyUrl: "URL取得",
    shareUrl: "共有URL",
    shareUrlCopied: "クリップボードにコピーしました",
    hashNotFound: "指定Hashが現在の結果に見つかりません。",

    progress: "進捗",
    best: "ベスト",
    selectedSeed: "選択中seed",

    searchSsot: "固定タイル",
    noSearchConfig: `templateIdに対応する検索設定がありません。src/gaia/ssot/searchPlacementConfig.ts に追加してください。`,
    templateMismatch:
      "表示中の盤面が選択中のテンプレートのものではないため、マーカーがタイル単位に劣化しています。人数・拡張の選択を盤面に合わせてください。",

    currentPlacementHash: "現在のHash",
    fixedLarge: "固定基本タイル",
    littlePool: "拡張小枠候補",
    scoutCount: "船枠数",

    logicalResults: "検索結果",
    currentLogicalSummary: "表示Map詳細",
    noCurrentResult: "現在の結果がありません（検索実行またはランク選択）。",

    placementHashResult: "HASH（評価）",
    placementHashView: "HASH（表示）",
    score: "スコア",
    rawScore: "rawScore",
    rankScore: "スコア",
    imbalance: "偏り",
    outerCnt: "最外周惑星数",
    touchCnt: "外周惑星数",

    trials: "検索件数",
    topK: "表示件数",
    totalSearched: "総検索数",
    speed: "速度",
    eta: "残り時間",

    resultsMode: "表示",
    resultsModeActive: "上位マップ",
    resultsModeUsed: "使用済み",
    markUsed: "使用済み",
    showing: "表示中",
    pin: "ピン留め",
    unpin: "ピン解除",
    restore: "未使用に戻す",
    delete: "完全削除",
    saved: "保存済み",
    savedConditions: "保存済み条件",
    tileModeLabel: "盤面表示",
    tileImage: "画像",
    tileSchematic: "番号＋向き",
    resetConditions: "既定値で新規",
    resetConditionsTip:
      "検索条件をすべて既定値に戻します。保存済み条件は起動時に自動適用されるため、既定値を変更したときはここから始めてください。保存済みのマップや条件は消えません。人数・拡張はそのままです。",
    confirmResetConditions: "検索条件をすべて既定値に戻します。よろしいですか？",
    savedConditionsShow: "表示",
    savedConditionsHide: "非表示",
    applyCondition: "適用",
    deleteMeta: "条件のみ削除",    deleteAll: "条件＋マップ削除",

    mapTools: "マップ調整",
    displaySettings: "表示設定",

    exportImportTitle: "エクスポート／インポート",
    exportAll: "全条件をエクスポート",
    exportCurrent: "現在の条件をエクスポート",
    importMode: "インポート方式",
    importMerge: "マージ",
    importReplace: "置換（危険）",
    importReplaceWarn: "全ての保存データを削除してからインポートします。",
    importChooseFile: "JSONファイルを選択",
    importRun: "インポート実行",
    importPreviewTitle: "インポート事前確認",
    importPreviewValid: "OK",
    importPreviewInvalid: "NG",
    importPreviewExportedAt: "エクスポート日時",
    importPreviewProfiles: "条件数",
    importPreviewCandidates: "マップ数",
    importPreviewSearchKeys: "条件キー数",
    importPreviewProfileConflicts: "既存条件と重複",
    importPreviewCandidateConflicts: "既存マップと重複",
    importPreviewFixups: "自動補完",
    importPreviewFixupsRank: "rankValue補完",
    importPreviewFixupsUsedKey: "usedKey補完",
    importPreviewFixupsId: "id補完",
    importReplaceConfirmLabel: "DELETE と入力すると置換が有効",
    importTooLargeNote: "注：巨大ファイルは衝突検査を一部省略します。",

    exportDone: "エクスポート完了",
    importDone: "インポート完了",
    importError: "インポートエラー",
    confirmDeleteMeta: "この保存済み条件（メタ情報）を削除しますか？（マップは残ります）",
    confirmDeleteAll: "この保存済み条件と関連する保存マップを全て削除しますか？（元に戻せません）",
    legacyUnknown: "旧データ（条件復元不可）",
    conditionName: "名前",
    unnamed: "（未設定）",
    editName: "編集",
    saveName: "保存",
    cancelName: "キャンセル",
    namePlaceholder: "例：大会用 / wScout高め",
    filter: "フィルタ",
    filterPlaceholder: "名前/条件で検索（例：wScout=6, std）",
    templateAll: "全て",
    clear: "クリア",


    hard: "制約条件",
    outerSameColorMax: "最外周同色上限",
    centerMode: "中央タイル制約",
    maxConnectedPlanets: "連結許容数",
    h5IncludeScouts: "探査船を含む",

    soft: "評価指数",
    metric: "指標",
    radius: "船接触半径",
    scoutRadiusLabel: "船接触半径",
    wOuter: "最外周評価",
    wTouch: "外周評価",
    wScout: "船接触",
    wScoutCore: "船星系",
    wScoutS1: "船接触(トワイライト)",
    wScoutS2: "船接触(エクリプス)",
    wScoutS3: "船接触(リベリオン)",
    wScoutS4: "船接触(TFマーズ)",
    wScoutCoreS1: "船星系(トワイライト)",
    wScoutCoreS2: "船星系(エクリプス)",
    wScoutCoreS3: "船星系(リベリオン)",
    wScoutCoreS4: "船星系(TFマーズ)",
    scoutCoreAttribBest: "船星系: 最大寄与に帰属",
    colorPreference: "色優遇/冷遇",
    wColorPref: "色優遇/冷遇の強さ",
    scoutRadius: "船接触半径",
    scoutTotal: "船接触点合計",
    scoutCoreRadius: "船星系半径",
    scoutCoreTotal: "船星系惑星数",
    extra: "船星系惑星数（中心拡張）",

    breakdown: "詳細",

    topKLogical: "ランク",

    hardFailCounts: "ハード失敗回数",

    glossary: "用語集",
    show: "表示",
    hide: "非表示",
    algoVersion: "探索version",
    evalVersion: "評価version",
    oldDataAvailable: "旧バージョンの保存データがあります（同一条件・別バージョン）",
    copyFrom: "コピー元",
    confirmCopy: "旧バージョンの候補を現バージョンにコピーしますか？（スコア再計算はしません）",

    // --- ホバーヒント（⑤ UI文言改善、2026-07-24）。title= で表示 ---
    tipTrials: "1回の検索で生成・評価する盤面の数",
    tipTopK: "スコア上位から保持・表示する件数",
    tipContinuous: "停止するまで検索を繰り返し、上位結果を蓄積します",
    tipHard: "満たさない盤面をその場で却下する条件",
    tipSoft: "却下されなかった盤面を順位付けする重み",
    tipOuterSameColorMax: "最外周（盤面の一番外の列）に置ける同色惑星の上限",
    tipMaxConnectedPlanets:
      "0=制限なし。Nを指定すると、隣接でつながった惑星のかたまりがN+1個以上ある盤面を却下します（ガイア/次元横断も連結に含む）",
    tipH5IncludeScouts: "上の連結判定に探査船セルも含めます",
    tipCenterMode: "中央スロットに入るタイルを制限します",
    tipWOuter: "最外周（一番外の列）の惑星1個あたりの重み（その色の合計に加算）",
    tipWTouch: "外周（最外周の1つ内側）の惑星1個あたりの重み",
    tipWScoutShip: "この船の接触半径内にある惑星1個あたりの重み",
    tipWScoutCoreShip:
      "この船が接触した惑星（船接触惑星）から距離1〜2にある惑星への重み。ただし距離1〜2に船接触惑星が2つ以上ある惑星だけを対象にします（1つだけなら対象外）。距離1は重み、距離2は重み−1で、複数の船接触惑星から届く分は合算します。ガイア惑星と次元横断惑星は船接触惑星に数えません。",
    tipScoutRadius: "船に接触しているとみなす距離",
    tipScoutCoreAttrib: "複数の船の圏内にある惑星を、寄与が最大の船だけに数えます",
    tipColorPref: "＋でその色が強い盤面を優遇、−で冷遇（重み×色合計がスコアに加算）",
    tipScore: "7色の強さが拮抗しているほど高くなります（偏りが小さいほど高評価）",
    tipHashPair:
      "HASH（評価）=選択中の検索結果の盤面／HASH（表示）=現在表示中の盤面。通常は一致し、シード手入力や共有リンク表示のときだけズレます",
    tipOuterCnt: "最外周（一番外の列）にある惑星の数",
    tipTouchCnt: "最外周の1つ内側にある惑星の数",
    tipResultsActive: "現在の条件で見つかった上位の保存マップ",
    tipResultsUsed: "「使用済み」にしたマップ（上位一覧には出ません）",
    tipPin: "Listタブに集約されます。保存上限による自動削除からも保護されます",
    tipMarkUsed: "使用済み一覧へ移動します（プレイ済みマップの記録用）",
    tipTotalCol: "その色の全評価軸の合計",
    extraAxesLF: "ガイア・星系を有効化",
    tipExtraAxesLF:
      "基本版のガイア近接・星系クラスタ軸を Lost Fleet でも使う。既定は ON です。OFF にするとこの2軸がキーから外れ、以前のLF結果バケットに戻ります（旧マップはコピーで引き継ぎ可能）。",
  },
} as const;

export type UiKey = keyof typeof UI_TEXT.en;
